on: 
   # push:
   #   branches: [ main ]
   # schedule:
   # - cron: '*/120 * * * *'
    workflow_dispatch:

jobs:
    run-monitor-job:
      runs-on: ubuntu-latest
      name: Carfax-url-monitor

      steps:
        - uses: actions/checkout@v2
          with:
            ref: Carfax
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - uses: browser-actions/setup-chrome@latest
        # running headless now - xvfb-run npm run test with more work to do headed
        - run: npm install
        - run: npm test
          env:
            APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY_DEMO_3}}
