on: 
   # push:
   #   branches: [ main ]
    schedule:
    - cron: '*/30 * * * *'
   # workflow_dispatch:

jobs:
    run-monitor-job:
      runs-on: ubuntu-latest
      name: url-monitor-is-my-name

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - uses: browser-actions/setup-chrome@latest
        # running headless now - xvfb-run npm run test with more work to do headed
        - run: npm install
        - run: npm test
          env:
            APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
