on:
  # push:
  #   branches: [ main ]
  # schedule:
  #  - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-monitor-job:
    runs-on: ubuntu-latest
    name: MITRE-url-monitor

    steps:
      - uses: actions/checkout@v2
        with:
          ref: Mitre
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: browser-actions/setup-chrome@latest
      # running headless now - xvfb-run npm run test with more work to do headed
      - run: npm install
      - run: |
          export DISPLAY=:99
          chromedrive & sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & npm test
        env:
          APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY_DEMO_2}}
